name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - mlflow=1.14.1
  - pandas=1.2.3
  - git=2.30.2
  - pip=20.3.3
  - pip:
      - wandb==0.10.31
      - matplotlib==3.5.1
      - cookiecutter==1.7.2
      - hydra-core==1.0.6